// <auto-generated />
using System;
using AStar.Clean.V1.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Clean.V1.Infrastructure.Migrations
{
    [DbContext(typeof(FilesDbContext))]
    [Migration("20230420101517_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AStar.Clean.V1.DomainModel.FileInfoJb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DetailsLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FileLastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Size" }, "IX_Size_Descending")
                        .IsDescending();

                    b.ToTable("FileInfo", "jjb");

                    b.HasData(
                        new
                        {
                            Id = new Guid("067a9f52-74ac-4a0c-aca8-f787903d5595"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1359),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "1. Create a new Wiki.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\1. Create a new Wiki.png",
                            Size = 34448L
                        },
                        new
                        {
                            Id = new Guid("291e0dbc-a127-4bef-a5f0-bea7f711ea07"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1397),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "2. Clone.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\2. Clone.png",
                            Size = 10092L
                        },
                        new
                        {
                            Id = new Guid("29b6d2e0-50ad-43c5-bcef-a12b3988c6de"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1406),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "2.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\2.jpg",
                            Size = 14610907L
                        },
                        new
                        {
                            Id = new Guid("34e38a94-81d0-4816-a726-2778822dd145"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1414),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "20220329_094236.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\20220329_094236.jpg",
                            Size = 9523777L
                        },
                        new
                        {
                            Id = new Guid("41f32591-c14f-4867-af3e-7c1e6723ef1c"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1422),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "3. Copy the selected file and folder.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\",
                            Size = 45388L
                        },
                        new
                        {
                            Id = new Guid("42ceae0f-3694-4060-8664-4d5d4e1ba825"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1432),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\3. Copy the selected file and folder.png",
                            Size = 1L
                        },
                        new
                        {
                            Id = new Guid("4f796939-bbeb-4f61-955a-409606378c4d"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1440),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "C&CA with MACE.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\C&CA with MACE.png",
                            Size = 10417L
                        },
                        new
                        {
                            Id = new Guid("581d98f2-2c33-4941-a873-20b6ab7fbe34"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1478),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "c&ca-logo-microsoft.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\c&ca-logo-microsoft.png",
                            Size = 20937L
                        },
                        new
                        {
                            Id = new Guid("5dc05c52-f64b-46f8-9db2-80d8f1b493db"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1489),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "c&ca-logo.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\c&ca-logo.png",
                            Size = 30379L
                        },
                        new
                        {
                            Id = new Guid("6473ad6f-f134-4443-8c8a-c87b19e06989"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1498),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "capgemini.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\capgemini.png",
                            Size = 5103L
                        },
                        new
                        {
                            Id = new Guid("6750d3bc-14a2-43f0-a10f-62bd1286f62c"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1506),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "d7e3b9c3d2a0101b74e30f0c448d9879.jfif",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\d7e3b9c3d2a0101b74e30f0c448d9879.jfif",
                            Size = 65964L
                        },
                        new
                        {
                            Id = new Guid("69da8471-1fb9-4e91-88c6-b6f8b4445ead"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1513),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "dates.webp",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\dates.webp",
                            Size = 62316L
                        },
                        new
                        {
                            Id = new Guid("7106bd02-49fe-48ca-8c07-6e849ddf4528"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1522),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "desktop.ini",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\desktop.ini",
                            Size = 520L
                        },
                        new
                        {
                            Id = new Guid("715c9823-4172-41fe-84d8-82d8bb271744"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1529),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "DTX Codes.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\DTX Codes.png",
                            Size = 89072L
                        },
                        new
                        {
                            Id = new Guid("7294fa9c-998d-48d8-8786-7da77b5e7430"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1537),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Example-of-Result-Object-Usage.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Example-of-Result-Object-Usage.png",
                            Size = 54927L
                        },
                        new
                        {
                            Id = new Guid("7657ea7d-339e-4a10-9a78-732a8f963556"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1546),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Failed.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Failed.png",
                            Size = 39925L
                        },
                        new
                        {
                            Id = new Guid("913a36ac-f1ce-4ebd-97fc-f02e6e5ea98c"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1553),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Galaxy S21 IMEI.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Galaxy S21 IMEI.jpg",
                            Size = 190660L
                        },
                        new
                        {
                            Id = new Guid("94b9d0ef-7ab6-4e51-a04c-40a3e818a4c1"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1562),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Galaxy S21.pdf",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Galaxy S21.pdf",
                            Size = 136996L
                        },
                        new
                        {
                            Id = new Guid("99937628-fdb8-4190-b3e9-7a8441d10f6e"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1570),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Had to change account permissions from reader.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Had to change account permissions from reader.png",
                            Size = 64552L
                        },
                        new
                        {
                            Id = new Guid("a393b8fe-84fa-475c-8808-aa17665fbbd9"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1581),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Handy.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Handy.png",
                            Size = 174083L
                        },
                        new
                        {
                            Id = new Guid("ad871b14-7589-4e4f-b369-a68e20665a12"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1589),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Image (6) - Copy.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Image (6) - Copy.jpg",
                            Size = 668673L
                        },
                        new
                        {
                            Id = new Guid("b2a4af69-15fa-41da-a328-b9941f25df8e"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1597),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Image (6)-2.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Image (6)-2.jpg",
                            Size = 112830L
                        },
                        new
                        {
                            Id = new Guid("b2d1c973-004c-497d-b942-f92eaaeee9ba"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1605),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Image (6).jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Image (6).jpg",
                            Size = 668673L
                        },
                        new
                        {
                            Id = new Guid("b7dec2eb-ef63-457f-8b82-da3e08fbdc7d"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1613),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "JayB.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\JayB.jpg",
                            Size = 15417L
                        },
                        new
                        {
                            Id = new Guid("b7dec2eb-ef63-457f-8b82-da3e08fbdc7e"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1620),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "MACE.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\MACE.png",
                            Size = 1583L
                        },
                        new
                        {
                            Id = new Guid("c888cf12-63e2-41a5-a5be-3d9570855b81"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1628),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "maxresdefault.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\maxresdefault.jpg",
                            Size = 67614L
                        },
                        new
                        {
                            Id = new Guid("d439a109-cb95-4e3c-afe8-984922b72806"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1635),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "o2 in PINK.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\o2 in PINK.jpg",
                            Size = 117992L
                        },
                        new
                        {
                            Id = new Guid("dbcdad60-7fd1-4de3-b6bb-67c93448bc22"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1642),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Screenshot 2020-10-12 092159.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Screenshot 2020-10-12 092159.png",
                            Size = 450910L
                        },
                        new
                        {
                            Id = new Guid("e0316f73-6ef7-4289-be97-27efd93b1eab"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1649),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "signature.jpg",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\signature.jpg",
                            Size = 11712L
                        },
                        new
                        {
                            Id = new Guid("e0316f73-6ef7-4289-be97-27efd93b1eac"),
                            DetailsLastUpdated = new DateTime(2023, 4, 20, 10, 15, 17, 35, DateTimeKind.Utc).AddTicks(1656),
                            DirectoryName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures",
                            FileLastUpdated = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Solution Structure.png",
                            FullName = "C:\\Users\\jbarden\\OneDrive - Capgemini\\Pictures\\Solution Structure.png",
                            Size = 58855L
                        });
                });

            modelBuilder.Entity("AStar.Clean.V1.DomainModel.FileInfoJb", b =>
                {
                    b.OwnsOne("AStar.Clean.V1.DomainModel.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("FileInfoJbId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Height")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<int?>("Width")
                                .HasColumnType("int")
                                .HasColumnName("Width");

                            b1.HasKey("FileInfoJbId");

                            b1.ToTable("FileInfo", "jjb");

                            b1.WithOwner()
                                .HasForeignKey("FileInfoJbId");
                        });

                    b.Navigation("Dimensions");
                });
#pragma warning restore 612, 618
        }
    }
}
