// <auto-generated />
using System;
using AStar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Infrastructure.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20240404000618_AddTagTables")]
    partial class AddTagTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("AStar.Infrastructure.Models.FileDetail", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailsLastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileName", "DirectoryName");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("AStar.Infrastructure.Models.TagToIgnore", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.ToTable("TagsToIgnore");
                });

            modelBuilder.Entity("AStar.Infrastructure.Models.TagToIgnoreCompletely", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Value");

                    b.ToTable("TagsToIgnoreCompletely");
                });
#pragma warning restore 612, 618
        }
    }
}
